import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {' '}
        <header>
          <nav>
            <a href="/">Home</a>
            <a href="/">About</a>
            <a href="/">Blog</a>
            <a href="/">Portefolio</a>
            <a href="/">Contact</a>
            <div className="animation start-home" />
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
